# Generated by Django 2.2.8 on 2020-06-09 18:11
from django.db import migrations
from hatespeech_models import Article
from django.utils.text import slugify

def set_slug(apps, schema_editor):
    for art in Article.objects:
        art.slug = slugify(art.title)[:50]
        art.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(set_slug)
    ]
